[package]
name = "next-proto"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
prost.workspace = true
prost-types.workspace = true
serde.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
